<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pharmacy;

class PharmacySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pharmacies = [
            [
                'codigo_cliente' => 'CLI000001',
                'nombre_comercial' => 'Farmacia San José',
                'razon_social' => 'FARMACIA SAN JOSÉ S.A.',
                'tipo_documento' => 'RUC',
                'numero_documento' => '1791234567001',
                'direccion' => 'Av. Amazonas N35-142 y Atahualpa',
                'ciudad' => 'Quito',
                'provincia' => 'Pichincha',
                'codigo_postal' => '170505',
                'telefono_principal' => '02-2234567',
                'telefono_secundario' => '0998765432',
                'email_principal' => 'gerencia@farmaciasanjose.com',
                'email_secundario' => 'compras@farmaciasanjose.com',
                'contacto_nombre' => 'María González',
                'contacto_cargo' => 'Gerente General',
                'contacto_telefono' => '0987654321',
                'limite_credito' => 15000.00,
                'dias_credito' => 30,
                'tipo_cliente' => 'mayorista',
                'descuento_general' => 5.00,
                'activo' => true,
                'horario_atencion' => 'Lunes a Viernes: 8:00 - 20:00, Sábados: 8:00 - 18:00',
                'zona_reparto' => 'Norte de Quito',
                'observaciones' => 'Cliente preferencial con historial de pagos excelente. Requiere entrega programada los martes y viernes.',
                'ultimo_pedido' => now()->subDays(5),
                'total_compras' => 125000.00,
                'created_by' => 1,
            ],
            [
                'codigo_cliente' => 'CLI000002',
                'nombre_comercial' => 'Farmacia El Centro',
                'razon_social' => 'DISTRIBUIDORA EL CENTRO CIA. LTDA.',
                'tipo_documento' => 'RUC',
                'numero_documento' => '1790123456001',
                'direccion' => 'Calle Mejía 453 y García Moreno',
                'ciudad' => 'Quito',
                'provincia' => 'Pichincha',
                'telefono_principal' => '02-2567890',
                'email_principal' => 'ventas@farmaciaelcentro.com',
                'contacto_nombre' => 'Carlos Pérez',
                'contacto_cargo' => 'Propietario',
                'contacto_telefono' => '0987123456',
                'limite_credito' => 8000.00,
                'dias_credito' => 15,
                'tipo_cliente' => 'regular',
                'descuento_general' => 2.50,
                'activo' => true,
                'horario_atencion' => 'Lunes a Sábado: 7:00 - 21:00',
                'zona_reparto' => 'Centro Histórico',
                'observaciones' => 'Farmacia tradicional del centro de la ciudad. Puntual en pagos.',
                'ultimo_pedido' => now()->subDays(12),
                'total_compras' => 65000.00,
                'created_by' => 1,
            ],
            [
                'codigo_cliente' => 'CLI000003',
                'nombre_comercial' => 'Farmacias Salud Total',
                'razon_social' => 'SALUD TOTAL S.A.',
                'tipo_documento' => 'RUC',
                'numero_documento' => '1792345678001',
                'direccion' => 'Av. 6 de Diciembre N26-85 y Lincoln',
                'ciudad' => 'Quito',
                'provincia' => 'Pichincha',
                'codigo_postal' => '170135',
                'telefono_principal' => '02-2890123',
                'telefono_secundario' => '0999888777',
                'email_principal' => 'administracion@saludtotal.com',
                'email_secundario' => 'logistica@saludtotal.com',
                'contacto_nombre' => 'Ana Rodríguez',
                'contacto_cargo' => 'Directora de Compras',
                'contacto_telefono' => '0988777666',
                'limite_credito' => 25000.00,
                'dias_credito' => 45,
                'tipo_cliente' => 'preferencial',
                'descuento_general' => 8.00,
                'activo' => true,
                'horario_atencion' => 'Lunes a Domingo: 24 horas',
                'zona_reparto' => 'La Mariscal',
                'observaciones' => 'Cadena de farmacias con 5 sucursales. Cliente VIP con descuentos especiales. Entrega diaria.',
                'ultimo_pedido' => now()->subDays(2),
                'total_compras' => 285000.00,
                'created_by' => 1,
            ],
            [
                'codigo_cliente' => 'CLI000004',
                'nombre_comercial' => 'Farmacia Guayaquil',
                'razon_social' => 'FARMACIA GUAYAQUIL HERMANOS S.A.',
                'tipo_documento' => 'RUC',
                'numero_documento' => '0991234567001',
                'direccion' => 'Av. 9 de Octubre 1579 y García Avilés',
                'ciudad' => 'Guayaquil',
                'provincia' => 'Guayas',
                'codigo_postal' => '090313',
                'telefono_principal' => '04-2345678',
                'email_principal' => 'info@farmaciaguayaquil.com',
                'contacto_nombre' => 'Roberto Silva',
                'contacto_cargo' => 'Gerente de Operaciones',
                'limite_credito' => 12000.00,
                'dias_credito' => 20,
                'tipo_cliente' => 'mayorista',
                'descuento_general' => 4.00,
                'activo' => true,
                'horario_atencion' => 'Lunes a Viernes: 8:00 - 19:00',
                'zona_reparto' => 'Centro de Guayaquil',
                'observaciones' => 'Farmacia histórica de Guayaquil con más de 50 años en el mercado.',
                'ultimo_pedido' => now()->subDays(8),
                'total_compras' => 98000.00,
                'created_by' => 1,
            ],
            [
                'codigo_cliente' => 'CLI000005',
                'nombre_comercial' => 'Farmacia Santa Clara',
                'razon_social' => 'SANTA CLARA PHARMACEUTICAL S.A.',
                'tipo_documento' => 'RUC',
                'numero_documento' => '1793456789001',
                'direccion' => 'Av. Eloy Alfaro N33-347 y 6 de Diciembre',
                'ciudad' => 'Quito',
                'provincia' => 'Pichincha',
                'telefono_principal' => '02-2456789',
                'email_principal' => 'contacto@santaclara.com',
                'contacto_nombre' => 'Patricia Morales',
                'contacto_cargo' => 'Administradora',
                'limite_credito' => 0.00,
                'dias_credito' => 0,
                'tipo_cliente' => 'regular',
                'descuento_general' => 0.00,
                'activo' => false,
                'horario_atencion' => 'Lunes a Viernes: 9:00 - 18:00',
                'zona_reparto' => 'Norte de Quito',
                'observaciones' => 'Cliente suspendido por pagos pendientes. Revisar antes de reactivar.',
                'ultimo_pedido' => now()->subDays(45),
                'total_compras' => 15000.00,
                'created_by' => 1,
            ]
        ];

        foreach ($pharmacies as $pharmacy) {
            Pharmacy::create($pharmacy);
        }
    }
}
