version: '1.0'

# Configuración para Coolify
# Este archivo define los comandos que se ejecutarán después del despliegue

post_deploy:
  - php artisan migrate:fresh --seed --force
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - php artisan optimize

