version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "828001"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=farmacia
      - DB_USERNAME=farmacia
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
    depends_on:
      - mysql
      - redis
    volumes:
      - storage:/var/www/html/storage
    networks:
      - farmacia-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: farmacia
      MYSQL_USER: farmacia
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - farmacia-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - farmacia-network

volumes:
  mysql-data:
  redis-data:
  storage:

networks:
  farmacia-network:
    driver: bridge