version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:82"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:82
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=farmacia
      - DB_USERNAME=farmacia
      - DB_PASSWORD=farmacia
    depends_on:
      - mysql
      - redis
    networks:
      - farmacia-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - farmacia-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmacia
      MYSQL_USER: farmacia
      MYSQL_PASSWORD: farmacia
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - farmacia-network

volumes:
  redis-data:
  mysql-data:

networks:
  farmacia-network:
    driver: bridge